// Datos simulados del Menú Diario (sin API).
// Dos objetivos físicos, cada uno con las 5 comidas del día.
// Todos los valores son de ejemplo y coherentes con cada objetivo.

const menuDiario = {
  ganar_musculo: [
    {
      tipo: "Desayuno",
      icono: "🥣",
      nombre: "Avena proteica con plátano y mantequilla de maní",
      descripcion:
        "Bowl de avena cocida en leche con proteína de suero, plátano y frutos secos para arrancar el día con energía.",
      ingredientes: [
        "80 g de avena en hojuelas",
        "250 ml de leche entera",
        "1 scoop de proteína de suero",
        "1 plátano",
        "15 g de mantequilla de maní",
        "10 g de nueces",
      ],
      calorias: 680,
      proteinas: 42,
      Precio: 5,
      carbohidratos: 72,
      grasas: 20,
      fibra: 10,
      vitaminas: ["B1", "B6", "E", "Ácido fólico"],
      minerales: ["Magnesio", "Fósforo", "Potasio", "Zinc"],
      macros: { proteinas: 42, carbohidratos: 72, grasas: 20 },
      micros: { sodio: 210, potasio: 720, magnesio: 140, calcio: 320 },
    },
    {
      tipo: "Snack de media mañana",
      icono: "🍎",
      nombre: "Yogur griego con arándanos y granola",
      descripcion:
        "Yogur griego alto en proteína con fruta fresca y granola crujiente para mantener la saciedad.",
      ingredientes: [
        "200 g de yogur griego natural",
        "80 g de arándanos",
        "30 g de granola",
        "1 cucharadita de miel",
      ],
      calorias: 340,
      proteinas: 24,
      carbohidratos: 38,
      grasas: 9,
      Precio: 5,
      fibra: 5,
      vitaminas: ["C", "K", "B2", "B12"],
      minerales: ["Calcio", "Fósforo", "Selenio"],
      macros: { proteinas: 24, carbohidratos: 38, grasas: 9 },
      micros: { sodio: 90, potasio: 350, magnesio: 45, calcio: 280 },
    },
    {
      tipo: "Almuerzo",
      icono: "🍛",
      nombre: "Pechuga de pollo con arroz integral y brócoli",
      descripcion:
        "Clásico plato de volumen: proteína magra, carbohidrato complejo y verdura al vapor.",
      ingredientes: [
        "180 g de pechuga de pollo",
        "120 g de arroz integral cocido",
        "150 g de brócoli",
        "1 cucharada de aceite de oliva",
        "Especias al gusto",
      ],
      calorias: 720,
      proteinas: 55,
      carbohidratos: 68,
      grasas: 22,
      Precio: 5,
      fibra: 8,
      vitaminas: ["B3", "B6", "C", "A"],
      minerales: ["Hierro", "Zinc", "Selenio", "Potasio"],
      macros: { proteinas: 55, carbohidratos: 68, grasas: 22 },
      micros: { sodio: 320, potasio: 810, magnesio: 120, calcio: 90 },
    },
    {
      tipo: "Snack de la tarde",
      icono: "🥜",
      nombre: "Batido de proteína con avena y almendras",
      descripcion:
        "Batido rápido post-entrenamiento para sumar proteína y calorías de calidad.",
      ingredientes: [
        "1 scoop de proteína de suero",
        "250 ml de leche",
        "30 g de avena",
        "15 g de almendras",
        "Hielo",
      ],
      calorias: 420,
      proteinas: 34,
      carbohidratos: 38,
      grasas: 14,
      Precio: 5,
      fibra: 6,
      vitaminas: ["E", "B2", "D"],
      minerales: ["Calcio", "Magnesio", "Fósforo"],
      macros: { proteinas: 34, carbohidratos: 38, grasas: 14 },
      micros: { sodio: 150, potasio: 480, magnesio: 110, calcio: 340 },
    },
    {
      tipo: "Cena",
      icono: "🥗",
      nombre: "Salmón al horno con quinoa y espárragos",
      descripcion:
        "Cena rica en proteína y grasas saludables (omega-3) para la recuperación muscular nocturna.",
      ingredientes: [
        "170 g de salmón",
        "100 g de quinoa cocida",
        "120 g de espárragos",
        "1 cucharada de aceite de oliva",
        "Limón y hierbas",
      ],
      calorias: 640,
      proteinas: 46,
      carbohidratos: 42,
      grasas: 28,
      Precio: 5,
      fibra: 7,
      vitaminas: ["D", "B12", "K", "A"],
      minerales: ["Omega-3", "Potasio", "Hierro", "Selenio"],
      macros: { proteinas: 46, carbohidratos: 42, grasas: 28 },
      micros: { sodio: 260, potasio: 690, magnesio: 130, calcio: 80 },
    },
  ],

  bajar_peso: [
    {
      tipo: "Desayuno",
      icono: "🥣",
      nombre: "Tortilla de claras con espinaca y tostada integral",
      descripcion:
        "Desayuno alto en proteína y bajo en calorías para un déficit sostenible y buena saciedad.",
      ingredientes: [
        "4 claras de huevo + 1 huevo entero",
        "50 g de espinaca",
        "1 rebanada de pan integral",
        "1/2 aguacate pequeño",
        "Tomate y especias",
      ],
      calorias: 320,
      proteinas: 26,
      carbohidratos: 24,
      grasas: 12,
      Precio: 5,
      fibra: 7,
      vitaminas: ["A", "C", "K", "Ácido fólico"],
      minerales: ["Hierro", "Potasio", "Magnesio"],
      macros: { proteinas: 26, carbohidratos: 24, grasas: 12 },
      micros: { sodio: 190, potasio: 520, magnesio: 70, calcio: 90 },
    },
    {
      tipo: "Snack de media mañana",
      icono: "🍎",
      nombre: "Manzana con un puñado de almendras",
      descripcion:
        "Snack natural y saciante que combina fibra y grasas saludables con pocas calorías.",
      ingredientes: ["1 manzana", "15 g de almendras", "Canela al gusto"],
      calorias: 180,
      proteinas: 5,
      carbohidratos: 24,
      grasas: 8,
      Precio: 5,
      fibra: 6,
      vitaminas: ["C", "E", "B2"],
      minerales: ["Potasio", "Magnesio", "Calcio"],
      macros: { proteinas: 5, carbohidratos: 24, grasas: 8 },
      micros: { sodio: 5, potasio: 260, magnesio: 55, calcio: 45 },
    },
    {
      tipo: "Almuerzo",
      icono: "🍛",
      nombre: "Ensalada de pollo, quinoa y vegetales",
      descripcion:
        "Plato completo, ligero y rico en fibra: proteína magra con un carbohidrato de bajo índice glucémico.",
      ingredientes: [
        "130 g de pechuga de pollo a la plancha",
        "60 g de quinoa cocida",
        "Mix de hojas verdes",
        "Pepino, tomate y zanahoria",
        "1 cucharada de aceite de oliva",
      ],
      calorias: 430,
      proteinas: 38,
      carbohidratos: 32,
      grasas: 15,
      Precio: 5,
      fibra: 9,
      vitaminas: ["A", "C", "B6", "K"],
      minerales: ["Hierro", "Potasio", "Zinc", "Magnesio"],
      macros: { proteinas: 38, carbohidratos: 32, grasas: 15 },
      micros: { sodio: 280, potasio: 640, magnesio: 95, calcio: 70 },
    },
    {
      tipo: "Snack de la tarde",
      icono: "🥜",
      nombre: "Yogur natural desnatado con semillas de chía",
      descripcion:
        "Snack proteico y bajo en grasa con chía para sumar fibra y prolongar la saciedad.",
      ingredientes: [
        "170 g de yogur natural desnatado",
        "10 g de semillas de chía",
        "1/2 taza de fresas",
      ],
      calorias: 160,
      proteinas: 16,
      carbohidratos: 16,
      grasas: 4,
      Precio: 5,
      fibra: 6,
      vitaminas: ["C", "B12", "B2"],
      minerales: ["Calcio", "Fósforo", "Magnesio"],
      macros: { proteinas: 16, carbohidratos: 16, grasas: 4 },
      micros: { sodio: 75, potasio: 300, magnesio: 60, calcio: 260 },
    },
    {
      tipo: "Cena",
      icono: "🥗",
      nombre: "Pescado blanco al vapor con verduras salteadas",
      descripcion:
        "Cena ligera y rica en proteína con abundante verdura para cerrar el día en déficit.",
      ingredientes: [
        "160 g de merluza o tilapia",
        "200 g de calabacín y pimiento",
        "1 cucharadita de aceite de oliva",
        "Ajo, limón y perejil",
      ],
      calorias: 300,
      proteinas: 34,
      carbohidratos: 14,
      grasas: 11,
      Precio: 5,
      fibra: 6,
      vitaminas: ["D", "C", "A", "B12"],
      minerales: ["Potasio", "Yodo", "Selenio", "Magnesio"],
      macros: { proteinas: 34, carbohidratos: 14, grasas: 11 },
      micros: { sodio: 230, potasio: 700, magnesio: 85, calcio: 60 },
    },
  ],
};

export default menuDiario;
